version: '3.8'
services:
  neo4j:
    image: neo4j:4.4.39-community
    ports:
      - 7888:7474
      - 7999:7687 #7999 db port web http://localhost:7888/browser/
    restart: unless-stopped
    environment:
      -  NEO4J_AUTH=neo4j/password
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins